name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
      - run: yarn test
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          AVAX_RPC_URL: ${{ secrets.AVAX_RPC_URL}}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn
      - run: yarn coverage
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          AVAX_RPC_URL: ${{ secrets.AVAX_RPC_URL}}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
      - uses: codecov/codecov-action@v3
