name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: echo ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }} >> .env
      - run: echo AVAX_RPC_URL=${{ secrets.AVAX_RPC_URL }} >> .env
      - run: echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env
      - run: yarn test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: echo ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }} >> .env
      - run: echo AVAX_RPC_URL=${{ secrets.AVAX_RPC_URL }} >> .env
      - run: echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env
      - run: yarn coverage
      - uses: codecov/codecov-action@v3
